Python 3.4.2 (default, Oct  8 2014, 13:08:17) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
			|Полиморфная вейвсеть				|Нейронная сеть

k2	|	S	|	n	|	M	|	dE	|	n	|	M	|	dE

0.033	|896.8~38.8	|1.0~0.0	|1898.9~506.4	|0.000~0.000	|14.5~5.1	|1467.2~459.4	|0.000~0.000

0.050	|403.4~11.9	|1.3~0.4	|1407.9~353.1	|0.000~0.000	|12.8~3.5	|1013.2~185.3	|0.000~0.000

0.075	|173.4~7.7	|1.1~0.3	|742.5~159.6	|0.000~0.000	|14.5~4.0	|634.2~129.8	|0.000~0.000

0.113	|79.1~3.0	|1.1~0.3	|410.3~89.5	|0.000~0.000	|17.5~4.0	|303.5~54.0	|0.000~0.000

0.169	|34.4~1.1	|2.9~1.5	|115.5~18.4	|0.000~0.000	|18.0~5.5	|161.5~23.9	|0.000~0.000

0.253	|15.3~0.5	|10.7~3.8	|57.0~7.9	|0.000~0.000	|20.0~6.9	|69.7~18.6	|0.000~0.000

0.380	|6.8~0.3	|49.5~27.3	|23.3~4.9	|0.000~0.000	|28.4~12.6	|32.2~4.9	|0.000~0.000
/usr/lib/python3/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/lib/python3/dist-packages/numpy/core/_methods.py:67: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/lib/python3/dist-packages/numpy/core/_methods.py:79: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/lib/python3/dist-packages/numpy/core/_methods.py:91: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/lib/python3/dist-packages/numpy/core/_methods.py:113: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

0.570	|3.1~0.1	|nan~nan	|11.4~1.0	|0.000~0.000	|25.9~16.9	|14.1~2.3	|0.000~0.000

0.854	|1.3~0.1	|nan~nan	|6.5~0.8	|0.001~0.000	|nan~nan	|5.4~0.9	|0.000~0.000

1.281	|0.6~0.0	|nan~nan	|3.3~0.6	|0.001~0.001	|nan~nan	|2.7~0.9	|0.001~0.000

Process /usr/bin/python3 finished

